extrinsic:
  # Calibration values from README. rotation_order is applied x -> y -> z.
  rotation_order: xyz
  cal_x: -881.97
  cal_y: 72.227
  cal_z: 838.867
  cal_rx: 178.454
  cal_ry: -1.685
  cal_rz: -90.682
