# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cmes_ai.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cmes_ai.proto',
  package='cmes_ai',
  syntax='proto3',
  serialized_options=b'\n\007ex.grpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rcmes_ai.proto\x12\x07\x63mes_ai\">\n\x07Request\x12\x1d\n\x15request_function_name\x18\x01 \x01(\t\x12\x14\n\x0crequest_data\x18\x02 \x01(\x0c\"8\n\x05Reply\x12\x1b\n\x13reply_function_name\x18\x01 \x01(\t\x12\x12\n\nreply_data\x18\x02 \x01(\x0c\x32>\n\x0e\x43mesAiExecutor\x12,\n\x06\x45xcute\x12\x10.cmes_ai.Request\x1a\x0e.cmes_ai.Reply\"\x00\x42\t\n\x07\x65x.grpcb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='cmes_ai.Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='request_function_name', full_name='cmes_ai.Request.request_function_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request_data', full_name='cmes_ai.Request.request_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=26,
  serialized_end=88,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='cmes_ai.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='reply_function_name', full_name='cmes_ai.Reply.reply_function_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reply_data', full_name='cmes_ai.Reply.reply_data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'cmes_ai_pb2'
  # @@protoc_insertion_point(class_scope:cmes_ai.Request)
  })
_sym_db.RegisterMessage(Request)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), {
  'DESCRIPTOR' : _REPLY,
  '__module__' : 'cmes_ai_pb2'
  # @@protoc_insertion_point(class_scope:cmes_ai.Reply)
  })
_sym_db.RegisterMessage(Reply)


DESCRIPTOR._options = None

_CMESAIEXECUTOR = _descriptor.ServiceDescriptor(
  name='CmesAiExecutor',
  full_name='cmes_ai.CmesAiExecutor',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=148,
  serialized_end=210,
  methods=[
  _descriptor.MethodDescriptor(
    name='Excute',
    full_name='cmes_ai.CmesAiExecutor.Excute',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_REPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CMESAIEXECUTOR)

DESCRIPTOR.services_by_name['CmesAiExecutor'] = _CMESAIEXECUTOR

# @@protoc_insertion_point(module_scope)
