# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import runner.modes.protos.cmes_ai_pb2 as cmes__ai__pb2


class CmesAiExecutorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Excute = channel.unary_unary(
                '/cmes_ai.CmesAiExecutor/Excute',
                request_serializer=cmes__ai__pb2.Request.SerializeToString,
                response_deserializer=cmes__ai__pb2.Reply.FromString,
                )


class CmesAiExecutorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Excute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CmesAiExecutorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Excute': grpc.unary_unary_rpc_method_handler(
                    servicer.Excute,
                    request_deserializer=cmes__ai__pb2.Request.FromString,
                    response_serializer=cmes__ai__pb2.Reply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cmes_ai.CmesAiExecutor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class CmesAiExecutor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Excute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/cmes_ai.CmesAiExecutor/Excute',
            cmes__ai__pb2.Request.SerializeToString,
            cmes__ai__pb2.Reply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
